const fs = require('fs');
let code = fs.readFileSync('src/components/AddFAB.tsx', 'utf8');

if (!code.includes('const dateInputRef')) {
  code = code.replace(
    'const [showSpanDropdown, setShowSpanDropdown] = useState(false);',
    'const [showSpanDropdown, setShowSpanDropdown] = useState(false);\n  const dateInputRef = useRef<HTMLInputElement>(null);\n  const timeInputRef = useRef<HTMLInputElement>(null);'
  );
}

const searchDate =                     <div className=\"relative\">\n                      <button type=\"button\" className=\"flex items-center gap-1.5 px-3.5 py-1.5 rounded-full bg-white border border-slate-200/80 text-slate-700 text-[12px] font-semibold transition-all shadow-sm\">\n                        <svg className=\"w-3.5 h-3.5 text-blue-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" strokeWidth=\"2.5\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" d=\"M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z\"></path></svg>\n                        {taskDate === todayStr ? '今天' : taskDate}\n                      </button>\n                      <input type=\"date\" value={taskDate} onChange={e => setTaskDate(e.target.value)} className=\"absolute inset-0 w-full h-full opacity-0 cursor-pointer [&::-webkit-calendar-picker-indicator]:absolute [&::-webkit-calendar-picker-indicator]:inset-0 [&::-webkit-calendar-picker-indicator]:w-full [&::-webkit-calendar-picker-indicator]:h-full [&::-webkit-calendar-picker-indicator]:cursor-pointer [&::-webkit-calendar-picker-indicator]:opacity-0\" required />\n                    </div>;

const replaceDate =                     <div className=\"relative\">\n                      <button type=\"button\" onClick={() => dateInputRef.current?.showPicker()} className=\"flex items-center gap-1.5 px-3.5 py-1.5 rounded-full bg-white border border-slate-200/80 text-slate-700 text-[12px] font-semibold transition-all shadow-sm\">\n                        <svg className=\"w-3.5 h-3.5 text-blue-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" strokeWidth=\"2.5\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" d=\"M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z\"></path></svg>\n                        {taskDate === todayStr ? '今天' : taskDate}\n                      </button>\n                      <input ref={dateInputRef} type=\"date\" value={taskDate} onChange={e => setTaskDate(e.target.value)} className=\"absolute w-0 h-0 opacity-0 pointer-events-none\" required />\n                    </div>;

const searchTime =                     {/* 截止时间 */}\n                    <div className=\"relative\">\n                      <button type=\"button\" className={\lex items-center gap-1.5 px-3.5 py-1.5 rounded-full border transition-all text-[12px] font-medium \\}>\n                        <svg className=\"w-3.5 h-3.5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" strokeWidth=\"2.5\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" d=\"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z\"></path></svg>\n                        {taskTime || '截止时间'}\n                      </button>\n                      <input type=\"time\" value={taskTime} onChange={e => setTaskTime(e.target.value)} className=\"absolute inset-0 w-full h-full opacity-0 cursor-pointer [&::-webkit-calendar-picker-indicator]:absolute [&::-webkit-calendar-picker-indicator]:inset-0 [&::-webkit-calendar-picker-indicator]:w-full [&::-webkit-calendar-picker-indicator]:h-full [&::-webkit-calendar-picker-indicator]:cursor-pointer [&::-webkit-calendar-picker-indicator]:opacity-0\" />\n                    </div>;

const replaceTime =                     {/* 截止时间 */}\n                    <div className=\"relative\">\n                      <button type=\"button\" onClick={() => timeInputRef.current?.showPicker()} className={\lex items-center gap-1.5 px-3.5 py-1.5 rounded-full border transition-all text-[12px] font-medium \\}>\n                        <svg className=\"w-3.5 h-3.5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" strokeWidth=\"2.5\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" d=\"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z\"></path></svg>\n                        {taskTime || '截止时间'}\n                      </button>\n                      <input ref={timeInputRef} type=\"time\" value={taskTime} onChange={e => setTaskTime(e.target.value)} className=\"absolute w-0 h-0 opacity-0 pointer-events-none\" />\n                    </div>;

code = code.replace(searchDate, replaceDate);
code = code.replace(searchTime, replaceTime);

fs.writeFileSync('src/components/AddFAB.tsx', code);
